### PR TITLE
Handle selection of one or more employers

### LINKED ISSUE #22: Employer field in profiles is not equivalent to the one in the built in blocks
The employer field doesn't offer an autoselect & when saved it creates a new relationship - but does not end the prior one

### PR DESCRIPTION
**Pull request by colemanw**
Fixes #22 
Now you can pick one or more employers as the "Current employer"

Now this extension actually handles the field better than core :/
We should port this functionality to core at some point, but probably will want to do one more step and have the "current employer" and "organization name" fields be serialized.

### CODE REVIEW

**Comment by colemanw** [comment]
Note: this depends on https://github.com/civicrm/org.civicrm.api4/pull/94

**Comment by colemanw** [comment]
@eileenmcnaughton let me know when you've tested this. There are a couple other PRs I'd like to submit but they will cause merge conflicts until this one gets merged.

**Comment by eileenmcnaughton** [comment]
@colemanw this works a treat. 

two non-blocking comments (which might already be on your radar)

1) This requires an update to apiv4 which might confuse people trying to download this from github (I realise you incremented info.xml in response). Since this is closely tied to api v4 at the moment (as both are maturing together) and since I think we envisage this shipping with core eventually it may make sense to do that sooner rather than later. It's pretty inobtrusive for those not using it.

2) the relationship count does not refresh when this is edited

3) (who's counting) erring on the side of safety might preclude adding start & end dates when they relationship is created via this field. We don't know when the relationship started & ended necessarily  - only when we edited their details. People who know the details can edit on the relationship tab or in a to-be-designed/ funded block per Nicolas's suggestion

**Comment by colemanw** [comment]
Thanks for the review. I've fixed 2 + 3 & merged.
For 1, I think anyone deploying from git ought to know better than to update one but not the other. But that doesn't mean they will.

**Pull request merged**
